services:
  aws:
    container_name: cypress-aws
    hostname: aws
    image: localstack/localstack
    ports:
      - 4566:4566           # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - app
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  e2e:
    image: cypress
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: e2e
    container_name: cypress
    env_file:
      - ./packages/e2e/.env
    networks:
      - app
    depends_on:
      - app
      - frontend
      - postgres
      - aws
    command: npx cypress open
    environment:
      - LOCALSTACK_HOSTNAME=aws
      - EDGE_PORT=4566
    volumes:
      - ./packages/e2e/cypress:/app/cypress
      - ./packages/e2e/cypress.config.js:/app/cypress.config.js
      - /tmp/.X11-unix:/tmp/.X11-unix
